### ISSUE TITLE
Make squirrel_perception compatible with travis

### ISSUE THREAD

**Issue by ipa-nhg** [squirrel-project/squirrel_perception#133]
I can't compile squirrel_perception with travis, the config files seems to be right. and with docker on a local computer I can compile the package, but travis says:

```
Errors     << squirrel_active_exploration:make /root/catkin_ws/logs/squirrel_active_exploration/build.make.000.log
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory
virtual memory exhausted: Cannot allocate memory

make[2]: *** [CMakeFiles/squirrel_active_exploration_common.dir/src/io_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/squirrel_active_exploration_common.dir/src/transform_utils.cpp.o] Error 1
make[2]: *** [CMakeFiles/squirrel_active_exploration_common.dir/src/pc_utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/squirrel_active_exploration_common.dir/all] Error 2
make: *** [all] Error 2
cd /root/catkin_ws/build/squirrel_active_exploration; catkin build --get-env squirrel_active_exploration | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
```

what is it suppose to do squirrel_active_exploration to compile?

**Comment by bajo** [comment]
I think it has to do with the 3GB memory limit of travis.
https://docs.travis-ci.com/user/common-build-problems/#My-build-script-is-killed-without-any-error
On my machine it takes more than 3GB to compile squirrel_perception. They suggest to turn down the number of parallel jobs. Can you test this in the travis config?

**Comment by ipa-nhg** [comment]
Thanks @bajo , lets try https://github.com/squirrel-project/squirrel_perception/pull/134

**Comment by bajo** [comment]
@ipa-nhg Seems that reducing the jobs is not enough. It takes more than 10 minutes to compile squirrel_active_perception. Travis stops if there is no output for more than 10 minutes. 
According to this, https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received, we can put a travis_wait in front of the build command to extend this to 20 minutes or use travis_wait xx to extend it to xx minutes if need be.

**Comment by ipa-nhg** [comment]
yes, trying with 30 minutes https://github.com/squirrel-project/squirrel_perception/pull/134/commits/a19cebd9f2e0e77dba3eb3c131602a780e4a1020

**Comment by ipa-nhg** [comment]
close https://github.com/squirrel-project/squirrel_perception/pull/134 , thanks @bajo for your support
